-- Add campaign steps configuration column
-- This stores the step-by-step configuration for each campaign

ALTER TABLE campaigns 
ADD COLUMN IF NOT EXISTS steps_config JSONB DEFAULT '[]'::JSONB;

-- Steps config structure:
-- [
--   {
--     "stepNumber": 1,
--     "type": "info" | "profile" | "rsvp" | "survey",
--     "title": "Step Title",
--     "content": { ... } // type-specific content
--   }
-- ]
--
-- For "info" type:
--   content: {
--     "greeting": "Hi, {first_name}",
--     "sections": [
--       {
--         "heading": "Important Information",
--         "items": ["Bullet point 1", "Bullet point 2"]
--       }
--     ],
--     "buttonText": "Next: Update My Profile →"
--   }
--
-- For "profile" type:
--   content: {
--     "fields": ["first_name", "last_name", "personal_email", ...] // array of field names to show
--   }
--
-- For "rsvp" type:
--   content: {
--     "eventTitle": "Annual Award Ceremony Luncheon",
--     "eventSubtitle": "We Made It!",
--     "eventDescription": "Join us to celebrate...",
--     "hostedBy": "CJE Media",
--     "when": "Tuesday, December 16 at 12:00 PM",
--     "where": "Rhay's Restaurant & Lounge, 11920 Westheimer Rd #J, Houston, TX 77077",
--     "rsvpBy": "December 9, 2025",
--     "dressCode": "Black Tie",
--     "eventFlyerUrl": "https://...",
--     "commentsPrompt": "Any dietary restrictions or special requests?",
--     "closingText": "Let's Celebrate!"
--   }
--
-- For "survey" type:
--   content: {
--     "questions": [
--       {
--         "id": "q1",
--         "type": "slider" | "textarea" | "radio" | "checkbox",
--         "label": "Question text",
--         "required": true,
--         "options": ["Option 1", "Option 2"], // for radio/checkbox
--         "min": 1, // for slider
--         "max": 10, // for slider
--         "minLabel": "Not supported", // for slider
--         "maxLabel": "Very supported" // for slider
--       }
--     ]
--   }

