-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  preferred_first_name text NOT NULL,
  preferred_last_name text NOT NULL,
  roles ARRAY DEFAULT ARRAY[]::text[],
  is_active boolean DEFAULT true,
  reset_token text,
  reset_token_expires timestamp with time zone,
  status text DEFAULT 'prospect'::text CHECK (status = ANY (ARRAY['prospect'::text, 'active'::text, 'inactive'::text])),
  personal_email text,
  personal_phone text,
  business_phone text,
  date_of_birth date,
  birth_month text,
  shirt_type text,
  shirt_size text,
  shipping_address_line1 text,
  shipping_address_line2 text,
  shipping_city text,
  shipping_state text,
  shipping_zip text,
  instagram_handle text,
  tiktok_handle text,
  threads_handle text,
  youtube_url text,
  linkedin_url text,
  facebook_url text,
  join_date date,
  office_email text,
  office text,
  license_number text,
  license_expiration date,
  nrds_id text,
  mls_id text,
  association text,
  association_status_on_join text,
  commission_plan text,
  commission_plan_other text,
  revenue_share text,
  additional_roles ARRAY,
  phone text,
  location text,
  mls_choice text,
  previous_brokerage text,
  expectations text,
  accountability text,
  lead_generation text,
  additional_info text,
  how_heard text,
  how_heard_other text,
  joining_team text,
  prospect_status text DEFAULT 'new'::text,
  notes jsonb DEFAULT '[]'::jsonb,
  campaign_token text UNIQUE,
  division ARRAY,
  referring_agent text,
  headshot_url text,
  headshot_crop jsonb,
  referred_agents ARRAY,
  referring_agent_id uuid,
  onboarding_fee_paid boolean DEFAULT false,
  onboarding_fee_paid_date date,
  monthly_fee_paid_through date,
  sales_count_current_year integer DEFAULT 0,
  total_sales_volume numeric,
  total_units_closed integer,
  total_agent_net numeric,
  job_title text,
  onedrive_folder_url text,
  role text,
  revenue_share_percentage numeric DEFAULT 2,
  payload_payee_id text,
  payload_payout_customer_id text,
  dashboard_links jsonb DEFAULT '[]'::jsonb,
  bank_connected boolean DEFAULT false,
  bank_connected_at timestamp with time zone,
  qualifying_transaction_count integer DEFAULT 0,
  sms_consent boolean DEFAULT false,
  sms_consent_date timestamp with time zone,
  sms_opted_out boolean DEFAULT false,
  sms_opted_out_date timestamp with time zone,
  timezone text DEFAULT 'America/Chicago'::text,
  special_commission_notes text,
  sales_volume_goal numeric DEFAULT 0,
  units_goal numeric DEFAULT 0,
  agent_net_goal numeric DEFAULT 0,
  goal_metric text DEFAULT 'volume'::text,
  active_goals ARRAY DEFAULT ARRAY['volume'::text, 'agent_net'::text],
  full_nav_access boolean DEFAULT false,
  accepted_trec boolean DEFAULT false,
  independent_contractor_agreement_signed boolean DEFAULT false,
  w9_completed boolean DEFAULT false,
  monthly_fee_waived boolean DEFAULT false,
  is_licensed_agent boolean DEFAULT true,
  waive_buyer_processing_fees boolean DEFAULT false,
  waive_seller_processing_fees boolean DEFAULT false,
  admin_notes text,
  ica_signed_at timestamp with time zone,
  ica_document_url text,
  commission_plan_agreement_signed boolean DEFAULT false,
  commission_plan_agreement_signed_at timestamp with time zone,
  commission_plan_agreement_url text,
  broker_signed_at timestamp with time zone,
  lease_commission_plan text DEFAULT 'lease'::text,
  qualifying_transaction_target integer NOT NULL DEFAULT 5,
  waive_coaching_fee boolean NOT NULL DEFAULT false,
  cap_amount_override numeric,
  post_cap_split_override text,
  new_signature_completed_at timestamp with time zone,
  is_coaching_client boolean NOT NULL DEFAULT false,
  w9_tin_status text,
  w9_form_id text,
  w9_signed_at timestamp with time zone,
  payload_activation_id text,
  payload_payment_method_id text,
  ms_refresh_token text,
  ms_oid text,
  first_login_at timestamp with time zone,
  canva_access_email_sent_at timestamp with time zone,
  half_buyer_processing_fees boolean NOT NULL DEFAULT false,
  half_seller_processing_fees boolean NOT NULL DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_users_referring_agent FOREIGN KEY (referring_agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text NOT NULL,
  year integer,
  deadline date NOT NULL,
  email_subject text,
  email_body text,
  sent_at timestamp with time zone,
  total_recipients integer DEFAULT 0,
  is_active boolean DEFAULT true,
  event_staff_email text,
  slug text UNIQUE,
  email_template_id uuid,
  steps_config jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_email_template_id_fkey FOREIGN KEY (email_template_id) REFERENCES public.email_templates(id)
);
CREATE TABLE public.campaign_recipients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  campaign_id uuid NOT NULL,
  user_id uuid NOT NULL,
  email_sent_at timestamp with time zone,
  email_opened_at timestamp with time zone,
  email_opened_count integer DEFAULT 0,
  link_clicked_at timestamp with time zone,
  step_1_completed_at timestamp with time zone,
  step_2_completed_at timestamp with time zone,
  step_3_completed_at timestamp with time zone,
  step_4_completed_at timestamp with time zone,
  fully_completed_at timestamp with time zone,
  current_step integer DEFAULT 0,
  CONSTRAINT campaign_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_recipients_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.campaign_responses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  campaign_id uuid NOT NULL,
  user_id uuid NOT NULL,
  commission_plan_2026 text,
  commission_plan_2026_other text,
  profile_updates jsonb DEFAULT '{}'::jsonb,
  attending_luncheon boolean,
  luncheon_comments text,
  support_rating integer,
  support_improvements text,
  work_preference text,
  submitted_at timestamp with time zone,
  CONSTRAINT campaign_responses_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_responses_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.email_tracking (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  campaign_recipient_id uuid NOT NULL,
  event_type text NOT NULL,
  user_agent text,
  ip_address text,
  CONSTRAINT email_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT email_tracking_campaign_recipient_id_fkey FOREIGN KEY (campaign_recipient_id) REFERENCES public.campaign_recipients(id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text NOT NULL UNIQUE,
  subject text NOT NULL,
  template_type text NOT NULL,
  design_type text NOT NULL,
  html_content text NOT NULL,
  preview_text text,
  is_default boolean DEFAULT false,
  created_by uuid,
  category text NOT NULL DEFAULT 'campaign'::text,
  description text,
  is_active boolean DEFAULT true,
  logo_url text DEFAULT '/logo.png'::text,
  subject_line text NOT NULL DEFAULT 'Campaign Email'::text,
  variables ARRAY DEFAULT ARRAY[]::text[],
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT email_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.listings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  agent_id uuid,
  agent_name text NOT NULL,
  client_names text NOT NULL,
  client_phone text,
  client_email text,
  property_address text NOT NULL,
  transaction_type text NOT NULL,
  mls_link text,
  mls_login_info text,
  estimated_launch_date date,
  actual_launch_date date,
  lead_source text,
  status text DEFAULT 'pre-listing'::text,
  pre_listing_form_completed boolean DEFAULT false,
  just_listed_form_completed boolean DEFAULT false,
  dotloop_file_created boolean DEFAULT false,
  photography_requested boolean DEFAULT false,
  photography_scheduled_date date,
  listing_input_requested boolean DEFAULT false,
  listing_input_paid boolean DEFAULT false,
  listing_input_fee numeric DEFAULT 50.00,
  notes jsonb DEFAULT '[]'::jsonb,
  listing_website_url text,
  closed_date date,
  mls_type text CHECK (mls_type IS NULL OR (mls_type = ANY (ARRAY['HAR'::text, 'NTREIS'::text]))),
  co_listing_agent text,
  is_broker_listing boolean DEFAULT false,
  loan_type text,
  team_agreement_id uuid,
  gross_commission numeric,
  brokerage_split_percentage numeric,
  agent_gross numeric,
  office_gross numeric,
  processing_fee numeric,
  new_agent_training_fee numeric,
  transaction_coordinator_fee numeric,
  document_prep_fee numeric,
  total_fees numeric,
  team_split_distributions jsonb,
  co_listing_agent_id uuid,
  co_listing_split_percentage numeric,
  co_listing_agent_gross numeric,
  co_listing_agent_fees numeric,
  co_listing_agent_net numeric,
  agent_net numeric,
  team_lead_net numeric,
  office_net numeric,
  cda_url text,
  agent_statement_sent boolean DEFAULT false,
  agent_statement_sent_date timestamp with time zone,
  submitted_for_compliance boolean DEFAULT false,
  compliance_approved boolean DEFAULT false,
  compliance_notes text,
  revenue_share_amount numeric,
  revenue_share_recipient_id uuid,
  revenue_share_recipient_name text,
  CONSTRAINT listings_pkey PRIMARY KEY (id),
  CONSTRAINT listings_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id),
  CONSTRAINT fk_listings_co_listing_agent FOREIGN KEY (co_listing_agent_id) REFERENCES public.users(id),
  CONSTRAINT listings_revenue_share_recipient_id_fkey FOREIGN KEY (revenue_share_recipient_id) REFERENCES public.users(id)
);
CREATE TABLE public.listing_coordination (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  listing_id uuid,
  agent_id uuid,
  service_fee numeric DEFAULT 250.00,
  service_paid boolean DEFAULT false,
  payment_date timestamp with time zone,
  is_active boolean DEFAULT true,
  start_date date NOT NULL,
  end_date date,
  seller_name text NOT NULL,
  seller_email text NOT NULL,
  onedrive_folder_url text,
  onedrive_folder_id text,
  email_schedule_day text DEFAULT 'monday'::text,
  email_schedule_time time without time zone DEFAULT '18:00:00'::time without time zone,
  last_email_sent_at timestamp with time zone,
  next_email_scheduled_for timestamp with time zone,
  welcome_email_sent boolean DEFAULT false,
  welcome_email_sent_at timestamp with time zone,
  total_emails_sent integer DEFAULT 0,
  notes jsonb DEFAULT '[]'::jsonb,
  seller_magic_link text UNIQUE,
  payment_method text CHECK (payment_method IS NULL OR (payment_method = ANY (ARRAY['client_direct'::text, 'agent_pays'::text, 'broker_listing'::text]))),
  payment_due_date date,
  CONSTRAINT listing_coordination_pkey PRIMARY KEY (id),
  CONSTRAINT listing_coordination_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.coordination_weekly_reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  coordination_id uuid,
  week_start_date date NOT NULL,
  week_end_date date NOT NULL,
  report_file_url text,
  report_file_name text,
  email_sent boolean DEFAULT false,
  email_sent_at timestamp with time zone,
  email_id text,
  email_status text,
  sent_to jsonb,
  showings_count integer,
  mls_views integer,
  feedback text,
  report_file_url_2 text,
  report_file_name_2 text,
  CONSTRAINT coordination_weekly_reports_pkey PRIMARY KEY (id),
  CONSTRAINT coordination_weekly_reports_coordination_id_fkey FOREIGN KEY (coordination_id) REFERENCES public.listing_coordination(id)
);
CREATE TABLE public.service_configurations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  service_type text NOT NULL UNIQUE,
  service_name text NOT NULL,
  service_description text,
  price numeric NOT NULL,
  payment_terms text,
  inclusions jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_configurations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.forms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text NOT NULL,
  description text,
  form_type text NOT NULL,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  shareable_token text UNIQUE,
  shareable_link_url text,
  form_config jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  notes text,
  notification_email text,
  notification_emails ARRAY DEFAULT '{}'::text[],
  triggers_flyer boolean DEFAULT false,
  flyer_type text,
  linked_form_type text,
  CONSTRAINT forms_pkey PRIMARY KEY (id),
  CONSTRAINT forms_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.revenue_share_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  recipient_agent_id uuid,
  recipient_name text,
  referred_agent_id uuid,
  referred_agent_name text,
  referred_agent_join_date date,
  onboarding_fee_amount numeric,
  revenue_share_percentage numeric,
  revenue_share_amount numeric,
  paid boolean DEFAULT false,
  paid_date date,
  notes text,
  ongoing_commission_share_percentage numeric,
  ongoing_commission_share_active boolean DEFAULT true,
  special_arrangement text,
  CONSTRAINT revenue_share_payments_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_share_payments_recipient_agent_id_fkey FOREIGN KEY (recipient_agent_id) REFERENCES public.users(id),
  CONSTRAINT revenue_share_payments_referred_agent_id_fkey FOREIGN KEY (referred_agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  document_type text,
  custom_document_name text,
  onedrive_folder_url text,
  onedrive_file_url text,
  uploaded_by uuid,
  upload_date date,
  notes text,
  version integer DEFAULT 1,
  is_current boolean DEFAULT true,
  document_category text,
  CONSTRAINT user_documents_pkey PRIMARY KEY (id),
  CONSTRAINT user_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transaction_type text,
  status text DEFAULT 'active'::text,
  representing text,
  property_address text,
  mls_number text,
  mls_type text,
  mls_link text,
  county text,
  area text,
  property_type text,
  lot_sqft numeric,
  building_sqft numeric,
  bedrooms integer,
  full_baths integer,
  half_baths integer,
  zoning text,
  apn text,
  legal_description text,
  public_remarks text,
  description text,
  listing_date date,
  listing_expiration_date date,
  buyer_agreement_date date,
  buyer_agreement_expiration_date date,
  acceptance_date date,
  closing_date date,
  closed_date date,
  office_location text,
  lead_source text,
  listing_website_url text,
  photography_requested boolean DEFAULT false,
  photography_scheduled_date date,
  listing_input_requested boolean DEFAULT false,
  listing_input_paid boolean DEFAULT false,
  listing_input_fee numeric,
  showing_instructions text,
  lockbox_serial_number text,
  yard_sign_post_rental boolean DEFAULT false,
  dotloop_file_created boolean DEFAULT false,
  pre_listing_form_completed boolean DEFAULT false,
  just_listed_form_completed boolean DEFAULT false,
  compliance_status text DEFAULT 'not_submitted'::text,
  compliance_notes text,
  cda_status text DEFAULT 'pending_compliance'::text,
  cda_url text,
  sales_price numeric,
  gross_commission numeric,
  listing_side_commission numeric,
  buying_side_commission numeric,
  office_gross numeric,
  office_net numeric,
  funding_status text,
  check_clear_date date,
  goal_paydate date,
  has_transaction_coordinator boolean DEFAULT false,
  transaction_coordinator_fee numeric,
  revenue_share_amount numeric,
  revenue_share_recipient_id uuid,
  legacy_listing_id uuid,
  notes jsonb,
  team_agreement_id uuid,
  sales_volume numeric,
  lease_term integer,
  representation_type text,
  gross_commission_type text DEFAULT 'amount'::text,
  listing_side_commission_type text DEFAULT 'amount'::text,
  buying_side_commission_type text DEFAULT 'amount'::text,
  is_locked boolean DEFAULT false,
  locked_at timestamp with time zone,
  locked_by uuid,
  submitted_by uuid,
  transaction_email text,
  move_in_date date,
  has_btsa boolean DEFAULT false,
  btsa_amount numeric DEFAULT 0,
  has_referral boolean DEFAULT false,
  has_ecommission boolean DEFAULT false,
  ecommission_amount numeric DEFAULT 0,
  compliance_submitted_at timestamp with time zone,
  compliance_submitted_by uuid,
  compliance_approved_at timestamp with time zone,
  compliance_approved_by uuid,
  cda_completed_at timestamp with time zone,
  cda_completed_by uuid,
  broker_approved_at timestamp with time zone,
  broker_approved_by uuid,
  closed_at timestamp with time zone,
  closed_by uuid,
  onedrive_folder_url text,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  monthly_rent numeric,
  client_name text,
  client_email text,
  client_phone text,
  title_officer_name text,
  title_company text,
  title_company_email text,
  bonus_amount numeric DEFAULT 0,
  rebate_amount numeric DEFAULT 0,
  internal_referral boolean DEFAULT false,
  internal_referral_fee numeric DEFAULT 0,
  external_referral boolean DEFAULT false,
  external_referral_fee numeric DEFAULT 0,
  expedite_requested boolean DEFAULT false,
  expedite_fee numeric DEFAULT 95,
  flyer_division text,
  additional_client_commission numeric DEFAULT 0,
  tenant_transaction_type text,
  info_confirmed_at timestamp with time zone,
  info_confirmed_by uuid,
  brokerage_referral boolean DEFAULT false,
  brokerage_referral_fee numeric DEFAULT 0,
  loan_type text,
  brokerage_referral_fee_type text DEFAULT 'percent'::text,
  internal_referral_fee_type text DEFAULT 'percent'::text,
  external_referral_fee_type text DEFAULT 'percent'::text,
  assigned_tc_id uuid,
  tc_activated_at timestamp with time zone,
  tc_contract_uploaded_at timestamp with time zone,
  effective_date date,
  earnest_option_money_due_date date,
  home_inspection_scheduled_by date,
  last_day_negotiate_repairs date,
  option_end_date date,
  appraisal_completed_by_date date,
  title_commitment_received_by date,
  tpfa_end_date date,
  final_walkthrough_date date,
  completion_date date,
  title_officer_phone text,
  client2_name text,
  client2_email text,
  homestead_county_id uuid,
  released_to_agent_at timestamp with time zone,
  is_intermediary boolean DEFAULT false,
  other_side_transaction_type text,
  listing_base_commission numeric,
  buying_base_commission numeric,
  street_address text,
  unit text,
  city text,
  state text,
  zip text,
  bathrooms numeric,
  garage integer,
  cda_sent_for_approval_at timestamp with time zone,
  cda_sent_manual_at timestamp with time zone,
  cda_sent_manual_by uuid,
  cda_manual_status text,
  archived_at timestamp with time zone,
  archived_by uuid,
  archive_reason text,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_revenue_share_recipient_id_fkey FOREIGN KEY (revenue_share_recipient_id) REFERENCES public.users(id),
  CONSTRAINT transactions_assigned_tc_id_fkey FOREIGN KEY (assigned_tc_id) REFERENCES public.users(id),
  CONSTRAINT transactions_homestead_county_id_fkey FOREIGN KEY (homestead_county_id) REFERENCES public.homestead_links(id),
  CONSTRAINT transactions_cda_sent_manual_by_fkey FOREIGN KEY (cda_sent_manual_by) REFERENCES public.users(id),
  CONSTRAINT transactions_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.users(id)
);
CREATE TABLE public.transaction_internal_agents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transaction_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  agent_role text NOT NULL,
  agent_role_other text,
  commission_plan text,
  commission_plan_id uuid,
  agent_basis numeric,
  split_percentage numeric,
  agent_gross numeric,
  processing_fee numeric DEFAULT 0,
  coaching_fee numeric DEFAULT 0,
  other_fees numeric DEFAULT 0,
  other_fees_description text,
  rebate_amount numeric DEFAULT 0,
  rebate_type text,
  btsa_amount numeric DEFAULT 0,
  agent_net numeric,
  amount_1099_reportable numeric,
  payment_status text DEFAULT 'pending'::text,
  payment_date date,
  payment_method text,
  payment_reference text,
  sales_volume numeric,
  units numeric DEFAULT 1,
  agent_statement_sent boolean DEFAULT false,
  agent_statement_sent_date timestamp with time zone,
  adjustment_notes text,
  pre_split_deductions numeric,
  pre_split_deductions_description text,
  agent_basis_type text DEFAULT 'amount'::text,
  pre_split_deductions_type text DEFAULT 'amount'::text,
  split_percentage_type text DEFAULT 'percent'::text,
  processing_fee_type text DEFAULT 'amount'::text,
  coaching_fee_type text DEFAULT 'amount'::text,
  other_fees_type text DEFAULT 'amount'::text,
  rebate_amount_type text DEFAULT 'amount'::text,
  btsa_amount_type text DEFAULT 'amount'::text,
  processing_fee_type_id uuid,
  team_lead_commission numeric DEFAULT 0,
  brokerage_split numeric DEFAULT 0,
  funding_source text DEFAULT 'crc'::text,
  debts_deducted numeric DEFAULT 0,
  counts_toward_progress boolean DEFAULT true,
  source_tia_id uuid,
  lead_source text,
  referred_agent_id uuid,
  uses_canonical_math boolean NOT NULL DEFAULT false,
  side text CHECK ((side = ANY (ARRAY['buyer'::text, 'seller'::text, 'tenant'::text, 'landlord'::text])) OR side IS NULL),
  installment_kind text CHECK (installment_kind IS NULL OR (installment_kind = ANY (ARRAY['retainer'::text, 'commission'::text]))),
  basis_input_mode text NOT NULL DEFAULT 'amount'::text CHECK (basis_input_mode = ANY (ARRAY['amount'::text, 'percentage'::text])),
  basis_percentage numeric,
  payment_sent_date date,
  CONSTRAINT transaction_internal_agents_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_internal_agents_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT transaction_internal_agents_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id),
  CONSTRAINT transaction_internal_agents_processing_fee_type_id_fkey FOREIGN KEY (processing_fee_type_id) REFERENCES public.processing_fee_types(id),
  CONSTRAINT transaction_internal_agents_source_tia_id_fkey FOREIGN KEY (source_tia_id) REFERENCES public.transaction_internal_agents(id),
  CONSTRAINT transaction_internal_agents_referred_agent_id_fkey FOREIGN KEY (referred_agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.transaction_external_brokerages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transaction_id uuid NOT NULL,
  brokerage_role text NOT NULL,
  brokerage_role_other text,
  brokerage_name text NOT NULL,
  brokerage_dba text,
  brokerage_ein text,
  brokerage_address text,
  brokerage_city text,
  brokerage_state text,
  brokerage_zip text,
  broker_name text,
  broker_phone text,
  broker_email text,
  agent_name text,
  agent_phone text,
  agent_email text,
  commission_amount numeric,
  amount_1099_reportable numeric,
  payment_status text DEFAULT 'pending'::text,
  payment_date date,
  payment_method text,
  payment_reference text,
  w9_on_file boolean DEFAULT false,
  w9_date_received date,
  federal_id_type text,
  federal_id_number text,
  notes text,
  side text CHECK ((side = ANY (ARRAY['buyer'::text, 'seller'::text, 'tenant'::text, 'landlord'::text])) OR side IS NULL),
  CONSTRAINT transaction_external_brokerages_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_external_brokerages_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.transaction_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transaction_id uuid NOT NULL,
  contact_type text NOT NULL,
  contact_type_other text,
  name text,
  phone jsonb,
  email jsonb,
  company text,
  notes text,
  CONSTRAINT transaction_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_contacts_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.agent_debts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  agent_id uuid NOT NULL,
  debt_type text NOT NULL,
  debt_type_other text,
  description text,
  amount_owed numeric NOT NULL,
  amount_paid numeric DEFAULT 0,
  amount_remaining numeric GENERATED ALWAYS AS (amount_owed - amount_paid) STORED,
  date_incurred date NOT NULL,
  due_date date,
  date_resolved date,
  status text DEFAULT 'outstanding'::text,
  offset_transaction_id uuid,
  offset_transaction_agent_id uuid,
  notes text,
  record_type text DEFAULT 'debt'::text,
  CONSTRAINT agent_debts_pkey PRIMARY KEY (id),
  CONSTRAINT agent_debts_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id),
  CONSTRAINT agent_debts_offset_transaction_id_fkey FOREIGN KEY (offset_transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT agent_debts_offset_transaction_agent_id_fkey FOREIGN KEY (offset_transaction_agent_id) REFERENCES public.transaction_internal_agents(id)
);
CREATE TABLE public.agent_w9s (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  agent_id uuid NOT NULL,
  legal_name text NOT NULL,
  business_name text,
  federal_id_type text NOT NULL,
  federal_id_number text NOT NULL,
  w9_address text,
  w9_city text,
  w9_state text,
  w9_zip text,
  date_received date,
  effective_date date,
  status text DEFAULT 'current'::text,
  notes text,
  version integer DEFAULT 1,
  is_current boolean DEFAULT true,
  CONSTRAINT agent_w9s_pkey PRIMARY KEY (id),
  CONSTRAINT agent_w9s_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.commission_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text NOT NULL,
  code text UNIQUE,
  description text,
  agent_split_percentage numeric NOT NULL,
  firm_split_percentage numeric NOT NULL,
  has_cap boolean DEFAULT false,
  cap_amount numeric,
  post_cap_agent_split numeric,
  processing_fee_amount numeric DEFAULT 399,
  coaching_fee_amount numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  notes text,
  post_cap_firm_split numeric,
  post_cap_split_type text DEFAULT 'percent'::text,
  agent_split_type text DEFAULT 'percent'::text,
  firm_split_type text DEFAULT 'percent'::text,
  min_transactions_to_upgrade integer,
  upgrade_to_plan_id uuid,
  CONSTRAINT commission_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transaction_flyers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transaction_id uuid,
  flyer_type text NOT NULL,
  status text DEFAULT 'requested'::text,
  requested_by uuid,
  sent_date timestamp with time zone,
  notes text,
  photo_url text,
  photo_uploaded_at timestamp with time zone,
  photo_uploaded_by uuid,
  nudge_sent_at timestamp with time zone,
  flyer_division text,
  city text,
  bedrooms text,
  bathrooms text,
  garage text,
  sqft text,
  custom_stats jsonb DEFAULT '[]'::jsonb,
  downloaded_at timestamp with time zone,
  downloaded_by uuid,
  source_form_id uuid,
  CONSTRAINT transaction_flyers_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_flyers_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT transaction_flyers_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id),
  CONSTRAINT transaction_flyers_photo_uploaded_by_fkey FOREIGN KEY (photo_uploaded_by) REFERENCES public.users(id),
  CONSTRAINT transaction_flyers_downloaded_by_fkey FOREIGN KEY (downloaded_by) REFERENCES public.users(id),
  CONSTRAINT transaction_flyers_source_form_id_fkey FOREIGN KEY (source_form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.processing_fee_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  processing_fee numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  display_order integer,
  counts_toward_cap boolean DEFAULT false,
  counts_toward_upgrade boolean DEFAULT true,
  is_lease boolean DEFAULT false,
  fee_type text DEFAULT 'flat'::text,
  additional_fee_description text,
  CONSTRAINT processing_fee_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_name text,
  legal_entity_name text,
  phone text,
  email text,
  website text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip text,
  logo_url text,
  logo_white_url text,
  compliance_email text,
  support_email text,
  support_phone text,
  training_center_url text,
  tools_home_url text,
  stripe_account_id text,
  payload_account_id text,
  onedrive_root_folder text,
  resend_from_domain text,
  twilio_phone text,
  btsa_min_sale_pct numeric DEFAULT 3,
  btsa_min_lease_pct numeric DEFAULT 50,
  check_clear_business_days integer DEFAULT 10,
  brokerage_income_split_pct numeric DEFAULT 25,
  onboarding_fee numeric DEFAULT 399,
  onboarding_fee_zelle numeric DEFAULT 399,
  monthly_fee numeric DEFAULT 50,
  contact_form_enabled boolean DEFAULT true,
  accent_color text DEFAULT '#C5A278'::text,
  accent_color_light text DEFAULT '#C5A27819'::text,
  default_sales_volume_goal numeric DEFAULT 1000000,
  bank_balance numeric DEFAULT 0,
  bank_balance_updated_at timestamp with time zone,
  referral_tracking_url text,
  crm_url text,
  crm_name text,
  funds_on_hold numeric DEFAULT 0,
  pm_notification_email text DEFAULT 'office@collectiverealtyco.com'::text,
  team_min_firm_sale_pct numeric DEFAULT 15,
  team_min_firm_lease_pct numeric DEFAULT 15,
  payload_pending_balance numeric DEFAULT 0,
  referral_conversion_free_until timestamp with time zone,
  referral_annual_fee numeric DEFAULT 299,
  referral_split_apartment integer DEFAULT 85,
  referral_split_internal integer DEFAULT 90,
  referral_split_external integer DEFAULT 88,
  referral_brokerage_name text DEFAULT 'Referral Collective'::text,
  referral_brokerage_email text DEFAULT 'referrals@collectiverealtyco.com'::text,
  referral_termination_notice_days integer DEFAULT 14,
  referral_payment_terms_days integer DEFAULT 30,
  referral_refund_period_days integer DEFAULT 90,
  brokerage_address_line1 text DEFAULT '13201 Northwest Fwy'::text,
  brokerage_address_line2 text DEFAULT 'Ste 450'::text,
  brokerage_city text DEFAULT 'Houston'::text,
  brokerage_state text DEFAULT 'Texas'::text,
  brokerage_zip text DEFAULT '77040'::text,
  brokerage_main_email text DEFAULT 'info@collectiverealtyco.com'::text,
  standard_onboarding_fee numeric DEFAULT 399,
  standard_monthly_fee numeric DEFAULT 50,
  standard_late_fee numeric DEFAULT 25,
  board_requirement_days integer DEFAULT 30,
  termination_notice_days integer DEFAULT 14,
  commission_payment_days integer DEFAULT 30,
  agency_name text DEFAULT 'Collective Realty Co.'::text,
  agency_email text DEFAULT 'info@collectiverealtyco.com'::text,
  apartment_invoice_fee numeric DEFAULT 100,
  referral_conversion_discount integer DEFAULT 0,
  executive_email text,
  standard_new_agent_coaching_fee numeric NOT NULL DEFAULT 500,
  standard_cap_amount numeric NOT NULL DEFAULT 18000,
  standard_post_cap_split text NOT NULL DEFAULT '97/3'::text,
  houston_address_line1 text DEFAULT '13201 Northwest Fwy'::text,
  houston_address_line2 text DEFAULT 'Ste 450'::text,
  houston_city text DEFAULT 'Houston'::text,
  houston_state text DEFAULT 'TX'::text,
  houston_zip text DEFAULT '77040'::text,
  houston_phone text DEFAULT '(281) 638-9407'::text,
  houston_fax text DEFAULT '(281) 516-5806'::text,
  dfw_address_line1 text DEFAULT '2300 Valley View Ln'::text,
  dfw_address_line2 text DEFAULT 'Ste 518'::text,
  dfw_city text DEFAULT 'Irving'::text,
  dfw_state text DEFAULT 'TX'::text,
  dfw_zip text DEFAULT '75062'::text,
  dfw_phone text DEFAULT ''::text,
  dfw_fax text DEFAULT ''::text,
  rc_brand_name text DEFAULT 'Referral Collective'::text,
  rc_address_line1 text DEFAULT '13201 Northwest Fwy'::text,
  rc_address_line2 text DEFAULT 'Ste 450'::text,
  rc_city text DEFAULT 'Houston'::text,
  rc_state text DEFAULT 'TX'::text,
  rc_zip text DEFAULT '77040'::text,
  rc_phone text DEFAULT '(281) 638-9407'::text,
  rc_fax text DEFAULT ''::text,
  rc_logo_url text DEFAULT 'https://zuhqqtfnyjlvbpcprdhf.supabase.co/storage/v1/object/public/public-assets/The%20Coaching%20Brokerage%20Final-01%20(1).png'::text,
  rc_website text DEFAULT 'https://coachingbrokerage.com'::text,
  zoom_recording_notification_email text,
  coaching_zoom_link text,
  coaching_client_zoom_link text,
  coaching_brokerage_name text,
  coaching_brokerage_email text,
  coaching_brokerage_address text,
  coaching_brokerage_website text,
  payload_commission_link_id text,
  payload_retainer_link_id text,
  payload_retainer_fee numeric DEFAULT 0,
  canva_username text,
  canva_password text,
  canva_url text,
  cda_due_soon_days integer NOT NULL DEFAULT 7,
  trec_broker_license_number text,
  license_report_email text,
  CONSTRAINT company_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.required_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  processing_fee_type_id uuid,
  name text NOT NULL,
  description text,
  is_required boolean DEFAULT true,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT required_documents_pkey PRIMARY KEY (id),
  CONSTRAINT required_documents_processing_fee_type_id_fkey FOREIGN KEY (processing_fee_type_id) REFERENCES public.processing_fee_types(id)
);
CREATE TABLE public.transaction_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transaction_id uuid NOT NULL,
  uploaded_by uuid,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size integer,
  file_type text,
  required_document_id uuid,
  compliance_status text DEFAULT 'pending'::text,
  compliance_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  version integer DEFAULT 1,
  onedrive_file_url text,
  onedrive_file_id text,
  tc_document_category text CHECK (tc_document_category IS NULL OR (tc_document_category = ANY (ARRAY['contract'::text, 'addenda'::text, 'amendment'::text]))),
  ai_review jsonb,
  submission_id uuid,
  CONSTRAINT transaction_documents_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_documents_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT transaction_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT transaction_documents_required_document_id_fkey FOREIGN KEY (required_document_id) REFERENCES public.required_documents(id),
  CONSTRAINT transaction_documents_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT transaction_documents_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.agent_form_submissions(id)
);
CREATE TABLE public.compliance_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  transaction_id uuid NOT NULL,
  reviewer_id uuid,
  status text DEFAULT 'in_progress'::text,
  notes text,
  completed_at timestamp with time zone,
  CONSTRAINT compliance_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_reviews_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT compliance_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id)
);
CREATE TABLE public.checklist_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  applies_to text DEFAULT 'both'::text,
  is_active boolean DEFAULT true,
  CONSTRAINT checklist_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.checklist_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  checklist_template_id uuid NOT NULL,
  section text NOT NULL,
  label text NOT NULL,
  description text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  auto_check_field text,
  CONSTRAINT checklist_items_pkey PRIMARY KEY (id),
  CONSTRAINT checklist_items_checklist_template_id_fkey FOREIGN KEY (checklist_template_id) REFERENCES public.checklist_templates(id)
);
CREATE TABLE public.checklist_completions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  transaction_id uuid NOT NULL,
  checklist_item_id uuid NOT NULL,
  completed_by uuid,
  completed_at timestamp with time zone DEFAULT now(),
  notes text,
  auto_verified boolean DEFAULT false,
  CONSTRAINT checklist_completions_pkey PRIMARY KEY (id),
  CONSTRAINT checklist_completions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT checklist_completions_checklist_item_id_fkey FOREIGN KEY (checklist_item_id) REFERENCES public.checklist_items(id),
  CONSTRAINT checklist_completions_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.users(id)
);
CREATE TABLE public.workflow_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  workflow_type text NOT NULL,
  step_number integer NOT NULL,
  title text NOT NULL,
  description text,
  left_panel_config jsonb DEFAULT '{}'::jsonb,
  right_panel_config jsonb DEFAULT '{}'::jsonb,
  applies_to text DEFAULT 'both'::text,
  is_active boolean DEFAULT true,
  CONSTRAINT workflow_steps_pkey PRIMARY KEY (id)
);
CREATE TABLE public.field_definitions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  processing_fee_type_id uuid,
  field_key text NOT NULL,
  label text NOT NULL,
  field_type text NOT NULL,
  options jsonb,
  is_required boolean DEFAULT false,
  required_on_compliance boolean DEFAULT false,
  show_on_verification boolean DEFAULT false,
  display_order integer DEFAULT 0,
  section text,
  placeholder text,
  help_text text,
  validation_rules jsonb,
  is_active boolean DEFAULT true,
  CONSTRAINT field_definitions_pkey PRIMARY KEY (id),
  CONSTRAINT field_definitions_processing_fee_type_id_fkey FOREIGN KEY (processing_fee_type_id) REFERENCES public.processing_fee_types(id)
);
CREATE TABLE public.checks_received (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transaction_id uuid,
  agent_id uuid,
  property_address text,
  check_amount numeric NOT NULL,
  check_number text,
  check_from text,
  check_image_url text,
  received_date date NOT NULL,
  deposited_date date,
  cleared_date date,
  brokerage_amount numeric,
  notes text,
  status text DEFAULT 'received'::text,
  compliance_complete_date date,
  crc_transferred boolean DEFAULT false,
  payment_method text DEFAULT 'check'::text,
  agents_paid boolean DEFAULT false,
  check_date date,
  hold_amount numeric DEFAULT 0,
  payload_transaction_id text,
  payload_payment_link_id text,
  CONSTRAINT checks_received_pkey PRIMARY KEY (id),
  CONSTRAINT checks_received_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT checks_received_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.check_payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  check_id uuid NOT NULL,
  payee_type text NOT NULL,
  user_id uuid,
  payee_name text,
  amount numeric NOT NULL,
  payment_status text DEFAULT 'pending'::text,
  payment_date date,
  payment_method text,
  payment_reference text,
  CONSTRAINT check_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT check_payouts_check_id_fkey FOREIGN KEY (check_id) REFERENCES public.checks_received(id),
  CONSTRAINT check_payouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payee_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  CONSTRAINT payee_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  CONSTRAINT activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.contact_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  name text NOT NULL,
  email text NOT NULL,
  subject text,
  message text NOT NULL,
  user_id uuid,
  status text DEFAULT 'new'::text,
  replied_by uuid,
  replied_at timestamp with time zone,
  CONSTRAINT contact_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT contact_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT contact_submissions_replied_by_fkey FOREIGN KEY (replied_by) REFERENCES public.users(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text NOT NULL UNIQUE,
  display_name text NOT NULL,
  description text,
  is_system boolean DEFAULT false,
  is_active boolean DEFAULT true,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  code text NOT NULL UNIQUE,
  display_name text NOT NULL,
  category text NOT NULL,
  description text,
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.role_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.user_permission_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  granted boolean NOT NULL,
  CONSTRAINT user_permission_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT user_permission_overrides_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_permission_overrides_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.notification_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  code text NOT NULL UNIQUE,
  display_name text NOT NULL,
  category text NOT NULL,
  description text,
  default_email boolean DEFAULT true,
  default_sms boolean DEFAULT false,
  delivery_timing text DEFAULT 'immediate'::text,
  is_mandatory boolean DEFAULT false,
  is_active boolean DEFAULT true,
  CONSTRAINT notification_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  notification_type_id uuid NOT NULL,
  email_enabled boolean,
  sms_enabled boolean,
  CONSTRAINT user_notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_notification_preferences_notification_type_id_fkey FOREIGN KEY (notification_type_id) REFERENCES public.notification_types(id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  session_id text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  ip_address text,
  user_agent text,
  is_valid boolean DEFAULT true,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.onboarding_checklist_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  section text NOT NULL,
  section_title text NOT NULL,
  item_key text NOT NULL,
  label text NOT NULL,
  description text,
  priority text DEFAULT 'normal'::text,
  link_text text,
  link_url text,
  second_link_text text,
  second_link_url text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT onboarding_checklist_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.onboarding_checklist_completions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  checklist_item_id uuid NOT NULL,
  completed_by uuid,
  completed_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT onboarding_checklist_completions_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_checklist_completions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT onboarding_checklist_completions_checklist_item_id_fkey FOREIGN KEY (checklist_item_id) REFERENCES public.onboarding_checklist_items(id),
  CONSTRAINT onboarding_checklist_completions_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.users(id)
);
CREATE TABLE public.onboarding_admin_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  label text NOT NULL,
  description text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  agent_variant text,
  CONSTRAINT onboarding_admin_tasks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.onboarding_admin_task_completions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  task_id uuid NOT NULL,
  completed_by uuid,
  completed_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT onboarding_admin_task_completions_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_admin_task_completions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT onboarding_admin_task_completions_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.onboarding_admin_tasks(id),
  CONSTRAINT onboarding_admin_task_completions_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.users(id)
);
CREATE TABLE public.onboarding_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL UNIQUE,
  current_step integer DEFAULT 1,
  reminder_count integer DEFAULT 0,
  last_reminder_sent_at timestamp with time zone,
  step_1_completed_at timestamp with time zone,
  step_2_completed_at timestamp with time zone,
  step_3_completed_at timestamp with time zone,
  step_4_completed_at timestamp with time zone,
  step_5_completed_at timestamp with time zone,
  step_6_completed_at timestamp with time zone,
  step_7_completed_at timestamp with time zone,
  fully_completed_at timestamp with time zone,
  ica_document_url text,
  commission_plan_document_url text,
  policy_ack_document_url text,
  w9_reference_id text,
  agent_signature_url text,
  payment_waived boolean DEFAULT false,
  discount_amount integer DEFAULT 0,
  previous_mls_choice text,
  CONSTRAINT onboarding_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payment_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  agent_id uuid,
  invoice_id text NOT NULL,
  payment_link_id text NOT NULL,
  url text NOT NULL,
  description text,
  amount numeric,
  status text DEFAULT 'active'::text,
  CONSTRAINT payment_links_pkey PRIMARY KEY (id),
  CONSTRAINT payment_links_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.training_center_bookmarks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resource_url text NOT NULL,
  resource_name text NOT NULL,
  resource_type text NOT NULL DEFAULT 'document'::text,
  category text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT training_center_bookmarks_pkey PRIMARY KEY (id),
  CONSTRAINT training_center_bookmarks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.training_center_announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT training_center_announcements_pkey PRIMARY KEY (id),
  CONSTRAINT training_center_announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.landlords (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text,
  mailing_address text,
  mailing_city text,
  mailing_state text DEFAULT 'TX'::text,
  mailing_zip text,
  dashboard_token text DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  track1099_reference_id text,
  track1099_form_request_id text,
  w9_status text DEFAULT 'not_started'::text,
  w9_tin_match_status text,
  w9_signed_at timestamp with time zone,
  w9_pdf_url text,
  payload_payee_id text,
  payload_payment_method_id text,
  payload_activation_id text,
  bank_status text DEFAULT 'not_started'::text,
  bank_connected_at timestamp with time zone,
  status text DEFAULT 'onboarding'::text,
  notes text,
  CONSTRAINT landlords_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text,
  dashboard_token text DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  payload_customer_id text,
  status text DEFAULT 'active'::text,
  notes text,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pm_agreements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  landlord_id uuid NOT NULL,
  commencement_date date NOT NULL,
  expiration_date date,
  auto_renews boolean DEFAULT true,
  management_fee_pct numeric NOT NULL DEFAULT 10,
  management_fee_minimum numeric,
  leasing_fee_pct numeric DEFAULT 75,
  leasing_fee_flat numeric,
  renewal_fee_pct numeric,
  renewal_fee_flat numeric DEFAULT 150,
  maintenance_coord_fee_pct numeric,
  eviction_fee numeric DEFAULT 350,
  repair_limit_without_approval numeric DEFAULT 250,
  reserve_per_unit numeric DEFAULT 500,
  lease_term_min_months integer DEFAULT 12,
  lease_term_max_months integer DEFAULT 24,
  coop_broker_fee_pct numeric DEFAULT 40,
  agreement_pdf_url text,
  status text DEFAULT 'active'::text,
  notes text,
  referring_agent_id uuid,
  agent_fee_pct numeric DEFAULT 0,
  management_fee_flat numeric,
  crc_collects_rent boolean NOT NULL DEFAULT true,
  crc_holds_deposit boolean NOT NULL DEFAULT true,
  crc_invoices_mgmt_fee boolean NOT NULL DEFAULT true,
  mgmt_fee_basis text NOT NULL DEFAULT 'charged'::text,
  CONSTRAINT pm_agreements_pkey PRIMARY KEY (id),
  CONSTRAINT pm_agreements_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id),
  CONSTRAINT pm_agreements_referring_agent_id_fkey FOREIGN KEY (referring_agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.managed_properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  landlord_id uuid NOT NULL,
  pm_agreement_id uuid,
  property_address text NOT NULL,
  unit text,
  city text NOT NULL,
  state text DEFAULT 'TX'::text,
  zip text,
  county text,
  unit_count integer DEFAULT 1,
  property_type text,
  bedrooms integer,
  bathrooms numeric,
  square_feet integer,
  year_built integer,
  hoa_name text,
  hoa_contact text,
  hoa_phone text,
  hoa_email text,
  status text DEFAULT 'active'::text,
  notes text,
  CONSTRAINT managed_properties_pkey PRIMARY KEY (id),
  CONSTRAINT managed_properties_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id),
  CONSTRAINT managed_properties_pm_agreement_id_fkey FOREIGN KEY (pm_agreement_id) REFERENCES public.pm_agreements(id)
);
CREATE TABLE public.pm_leases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  property_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  landlord_id uuid NOT NULL,
  source_transaction_id uuid,
  lease_start date NOT NULL,
  lease_end date NOT NULL,
  move_in_date date,
  monthly_rent numeric NOT NULL,
  rent_due_day integer DEFAULT 1,
  security_deposit numeric DEFAULT 0,
  late_fee_grace_days integer DEFAULT 2,
  late_fee_initial numeric,
  late_fee_daily numeric,
  late_fee_max_days integer,
  late_fee_cap_pct numeric,
  returned_payment_fee numeric DEFAULT 150,
  lease_pdf_url text,
  status text DEFAULT 'active'::text,
  notes text,
  landlord_payment_instructions text,
  CONSTRAINT pm_leases_pkey PRIMARY KEY (id),
  CONSTRAINT pm_leases_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.managed_properties(id),
  CONSTRAINT pm_leases_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT pm_leases_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id)
);
CREATE TABLE public.tenant_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  property_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  landlord_id uuid NOT NULL,
  lease_id uuid,
  period_month integer NOT NULL,
  period_year integer NOT NULL,
  rent_amount numeric NOT NULL,
  late_fee numeric DEFAULT 0,
  other_charges numeric DEFAULT 0,
  other_charges_description text,
  total_amount numeric NOT NULL,
  due_date date NOT NULL,
  late_fee_applied_at timestamp with time zone,
  payload_invoice_id text,
  payload_payment_link_id text,
  payload_payment_link_url text,
  status text DEFAULT 'pending'::text,
  paid_at timestamp with time zone,
  paid_amount numeric,
  payment_method text,
  notes text,
  deposit_amount numeric NOT NULL DEFAULT 0,
  deposit_description text,
  funds_cleared_at date,
  CONSTRAINT tenant_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_invoices_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.managed_properties(id),
  CONSTRAINT tenant_invoices_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_invoices_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id),
  CONSTRAINT tenant_invoices_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES public.pm_leases(id)
);
CREATE TABLE public.landlord_disbursements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  landlord_id uuid NOT NULL,
  tenant_invoice_id uuid,
  property_id uuid,
  lease_id uuid,
  gross_rent numeric NOT NULL,
  management_fee numeric NOT NULL,
  other_deductions numeric DEFAULT 0,
  other_deductions_description text,
  net_amount numeric NOT NULL,
  payment_status text DEFAULT 'pending'::text,
  payment_date date,
  payload_payout_id text,
  amount_1099_reportable numeric,
  period_month integer,
  period_year integer,
  notes text,
  payment_method text,
  payment_reference text,
  deposit_amount numeric NOT NULL DEFAULT 0,
  disbursement_type text NOT NULL DEFAULT 'rent'::text,
  reserve_amount numeric NOT NULL DEFAULT 0,
  owner_charges_amount numeric NOT NULL DEFAULT 0,
  CONSTRAINT landlord_disbursements_pkey PRIMARY KEY (id),
  CONSTRAINT landlord_disbursements_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id),
  CONSTRAINT landlord_disbursements_tenant_invoice_id_fkey FOREIGN KEY (tenant_invoice_id) REFERENCES public.tenant_invoices(id),
  CONSTRAINT landlord_disbursements_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.managed_properties(id),
  CONSTRAINT landlord_disbursements_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES public.pm_leases(id)
);
CREATE TABLE public.pm_auth_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_type text NOT NULL CHECK (user_type = ANY (ARRAY['landlord'::text, 'tenant'::text])),
  user_id uuid NOT NULL,
  email text NOT NULL,
  token text NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:15:00'::interval),
  used_at timestamp with time zone,
  ip_address text,
  user_agent text,
  CONSTRAINT pm_auth_tokens_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pm_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_type text NOT NULL CHECK (user_type = ANY (ARRAY['landlord'::text, 'tenant'::text])),
  user_id uuid NOT NULL,
  email text NOT NULL,
  session_token text NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  ip_address text,
  user_agent text,
  last_accessed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pm_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pm_access_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_type text NOT NULL,
  user_id uuid NOT NULL,
  email text,
  action text NOT NULL,
  ip_address text,
  user_agent text,
  CONSTRAINT pm_access_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.repair_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  property_id uuid NOT NULL,
  tenant_id uuid,
  landlord_id uuid NOT NULL,
  lease_id uuid,
  created_by_type text NOT NULL DEFAULT 'tenant'::text CHECK (created_by_type = ANY (ARRAY['tenant'::text, 'admin'::text])),
  created_by_admin_id uuid,
  category text NOT NULL CHECK (category = ANY (ARRAY['plumbing'::text, 'electrical'::text, 'hvac'::text, 'appliance'::text, 'structural'::text, 'pest'::text, 'landscaping'::text, 'other'::text])),
  urgency text NOT NULL DEFAULT 'routine'::text CHECK (urgency = ANY (ARRAY['emergency'::text, 'urgent'::text, 'routine'::text])),
  title text NOT NULL,
  description text,
  photos jsonb DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['submitted'::text, 'approved'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  vendor_name text,
  vendor_phone text,
  vendor_email text,
  estimated_cost numeric,
  actual_cost numeric,
  invoice_url text,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'landlord_paid'::text, 'deducted_from_rent'::text, 'not_applicable'::text])),
  payment_date date,
  deducted_from_disbursement_id uuid,
  completed_at timestamp with time zone,
  admin_notes text,
  messages jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT repair_requests_pkey PRIMARY KEY (id),
  CONSTRAINT repair_requests_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.managed_properties(id),
  CONSTRAINT repair_requests_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT repair_requests_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id),
  CONSTRAINT repair_requests_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES public.pm_leases(id),
  CONSTRAINT repair_requests_created_by_admin_id_fkey FOREIGN KEY (created_by_admin_id) REFERENCES public.users(id),
  CONSTRAINT repair_requests_deducted_from_disbursement_id_fkey FOREIGN KEY (deducted_from_disbursement_id) REFERENCES public.landlord_disbursements(id)
);
CREATE TABLE public.pm_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  landlord_id uuid NOT NULL,
  property_id uuid,
  entry_type text NOT NULL CHECK (entry_type = ANY (ARRAY['rent_received'::text, 'management_fee'::text, 'repair_expense'::text, 'repair_payment'::text, 'disbursement'::text, 'security_deposit_in'::text, 'security_deposit_out'::text, 'other_income'::text, 'other_expense'::text])),
  description text NOT NULL,
  amount numeric NOT NULL,
  reference_type text CHECK (reference_type = ANY (ARRAY['tenant_invoice'::text, 'repair_request'::text, 'landlord_disbursement'::text, 'manual'::text])),
  reference_id uuid,
  period_month integer CHECK (period_month >= 1 AND period_month <= 12),
  period_year integer CHECK (period_year >= 2020 AND period_year <= 2100),
  CONSTRAINT pm_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT pm_ledger_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id),
  CONSTRAINT pm_ledger_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.managed_properties(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_name text NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  CONSTRAINT teams_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  team_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date,
  CONSTRAINT team_leads_pkey PRIMARY KEY (id),
  CONSTRAINT team_leads_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_leads_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.team_member_agreements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  effective_date date NOT NULL,
  end_date date,
  agreement_document_url text,
  firm_min_override boolean DEFAULT false,
  notes text,
  CONSTRAINT team_member_agreements_pkey PRIMARY KEY (id),
  CONSTRAINT team_member_agreements_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_member_agreements_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.team_agreement_splits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  agreement_id uuid NOT NULL,
  plan_type text NOT NULL CHECK (plan_type = ANY (ARRAY['sales_70_30'::text, 'sales_85_15'::text, 'leases'::text])),
  lead_source text NOT NULL CHECK (lead_source = ANY (ARRAY['team_lead'::text, 'own'::text, 'firm'::text])),
  agent_pct numeric NOT NULL,
  team_lead_pct numeric NOT NULL,
  firm_pct numeric NOT NULL,
  CONSTRAINT team_agreement_splits_pkey PRIMARY KEY (id),
  CONSTRAINT team_agreement_splits_agreement_id_fkey FOREIGN KEY (agreement_id) REFERENCES public.team_member_agreements(id)
);
CREATE TABLE public.brokerage_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  entry_date date NOT NULL,
  entry_type text NOT NULL CHECK (entry_type = ANY (ARRAY['income'::text, 'expense'::text])),
  category text NOT NULL,
  subcategory text,
  description text NOT NULL,
  amount numeric NOT NULL,
  agent_id uuid,
  transaction_id uuid,
  bank_reference text,
  bank_date date,
  reconciled boolean DEFAULT false,
  reconciled_at timestamp with time zone,
  reconciled_by uuid,
  external_source text,
  external_id text,
  notes text,
  CONSTRAINT brokerage_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT brokerage_ledger_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id),
  CONSTRAINT brokerage_ledger_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT brokerage_ledger_reconciled_by_fkey FOREIGN KEY (reconciled_by) REFERENCES public.users(id)
);
CREATE TABLE public.payout_expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  description text NOT NULL,
  amount numeric,
  CONSTRAINT payout_expenses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pm_fee_payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  disbursement_id uuid NOT NULL,
  payee_type text NOT NULL CHECK (payee_type = ANY (ARRAY['agent'::text, 'brokerage'::text])),
  payee_id uuid,
  payee_name text NOT NULL,
  amount numeric NOT NULL,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'processing'::text, 'paid'::text, 'failed'::text])),
  payment_date date,
  payment_method text,
  payment_reference text,
  notes text,
  landlord_invoice_id uuid,
  amount_1099_reportable numeric,
  CONSTRAINT pm_fee_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT pm_fee_payouts_disbursement_id_fkey FOREIGN KEY (disbursement_id) REFERENCES public.landlord_disbursements(id),
  CONSTRAINT pm_fee_payouts_payee_id_fkey FOREIGN KEY (payee_id) REFERENCES public.users(id),
  CONSTRAINT pm_fee_payouts_landlord_invoice_id_fkey FOREIGN KEY (landlord_invoice_id) REFERENCES public.pm_landlord_invoices(id)
);
CREATE TABLE public.commission_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rule_key text NOT NULL UNIQUE,
  rule_name text NOT NULL,
  description text,
  agent_split integer,
  brokerage_split integer,
  minimum_percent numeric,
  minimum_description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT commission_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.document_signing_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  signer_id uuid,
  signer_type text NOT NULL CHECK (signer_type = ANY (ARRAY['agent'::text, 'broker'::text, 'landlord'::text, 'tenant'::text, 'team_lead'::text, 'admin'::text])),
  signer_name text NOT NULL,
  document_type text NOT NULL,
  pdf_url text,
  ip_address text,
  user_agent text,
  signature_data_url text,
  is_final_version boolean DEFAULT false,
  superseded_by uuid,
  document_subtype text,
  related_entity_type text,
  related_entity_id uuid,
  signed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_signing_events_pkey PRIMARY KEY (id),
  CONSTRAINT document_signing_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT document_signing_events_signer_id_fkey FOREIGN KEY (signer_id) REFERENCES public.users(id),
  CONSTRAINT document_signing_events_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES public.document_signing_events(id)
);
CREATE TABLE public.calendar_reminder_logs (
  event_id text NOT NULL,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT calendar_reminder_logs_pkey PRIMARY KEY (event_id)
);
CREATE TABLE public.preferred_vendors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_type text NOT NULL CHECK (vendor_type = ANY (ARRAY['inspection'::text, 'insurance'::text, 'home_warranty'::text, 'title'::text, 'lender'::text, 'other'::text])),
  company_name text NOT NULL,
  contact_name text,
  phone text,
  email text,
  display_order integer DEFAULT 0,
  is_featured boolean DEFAULT true,
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT preferred_vendors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tc_email_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['buyer'::text, 'nc_buyer'::text, 'seller'::text, 'all'::text])),
  category text NOT NULL,
  subject text NOT NULL,
  body_format text NOT NULL DEFAULT 'html'::text CHECK (body_format = ANY (ARRAY['html'::text, 'plain_text'::text])),
  html_body text,
  plain_body text,
  default_recipient_roles jsonb NOT NULL DEFAULT '{}'::jsonb,
  attach_documents jsonb DEFAULT '[]'::jsonb,
  uses_banner boolean DEFAULT false,
  uses_signature boolean DEFAULT true,
  is_active boolean DEFAULT true,
  notes text,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tc_email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT tc_email_templates_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.tc_process_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['buyer'::text, 'nc_buyer'::text, 'seller'::text])),
  step_order integer NOT NULL,
  step_type text NOT NULL CHECK (step_type = ANY (ARRAY['email'::text, 'agent_task'::text, 'tc_task'::text, 'office_task'::text, 'compliance_review'::text])),
  title text NOT NULL,
  description text,
  owner text CHECK (owner IS NULL OR (owner = ANY (ARRAY['tc'::text, 'agent'::text, 'office'::text]))),
  template_id uuid,
  anchor text CHECK (anchor IS NULL OR (anchor = ANY (ARRAY['effective_date'::text, 'option_end_date'::text, 'tpfa_end_date'::text, 'closing_date'::text, 'completion_date'::text]))),
  offset_days integer,
  recurrence text DEFAULT 'none'::text CHECK (recurrence = ANY (ARRAY['none'::text, 'mon_thu'::text, 'weekly'::text])),
  recurrence_end_anchor text,
  recurrence_end_offset integer,
  is_conditional boolean DEFAULT false,
  condition_description text,
  needs_approval_by_default boolean DEFAULT false,
  show_on_calendar boolean DEFAULT false,
  is_active boolean DEFAULT true,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tc_process_steps_pkey PRIMARY KEY (id),
  CONSTRAINT tc_process_steps_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.tc_email_templates(id),
  CONSTRAINT tc_process_steps_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.tc_scheduled_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_id uuid NOT NULL,
  process_step_id uuid,
  scheduled_for timestamp with time zone NOT NULL,
  original_scheduled_for timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'needs_approval'::text, 'approved'::text, 'sent'::text, 'skipped'::text, 'cancelled'::text, 'failed'::text])),
  recipients_resolved jsonb,
  subject_resolved text,
  body_resolved text,
  attachment_doc_ids ARRAY,
  needs_shift_approval boolean DEFAULT false,
  shift_reason text,
  last_shifted_at timestamp with time zone,
  sent_at timestamp with time zone,
  sent_by_user_id uuid,
  sent_from_user_id uuid,
  sent_via text CHECK (sent_via IS NULL OR (sent_via = ANY (ARRAY['graph'::text, 'resend'::text]))),
  graph_message_id text,
  skipped_at timestamp with time zone,
  skipped_by_user_id uuid,
  skipped_reason text,
  calendar_event_id text,
  send_attempts integer DEFAULT 0,
  last_error text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tc_scheduled_events_pkey PRIMARY KEY (id),
  CONSTRAINT tc_scheduled_events_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT tc_scheduled_events_process_step_id_fkey FOREIGN KEY (process_step_id) REFERENCES public.tc_process_steps(id),
  CONSTRAINT tc_scheduled_events_sent_by_user_id_fkey FOREIGN KEY (sent_by_user_id) REFERENCES public.users(id),
  CONSTRAINT tc_scheduled_events_sent_from_user_id_fkey FOREIGN KEY (sent_from_user_id) REFERENCES public.users(id),
  CONSTRAINT tc_scheduled_events_skipped_by_user_id_fkey FOREIGN KEY (skipped_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.tc_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  banner_image_url text,
  signature_html_template text,
  tc_calendar_group_id text,
  office_email text DEFAULT 'office@collectiverealtyco.com'::text,
  office_phone text,
  default_reply_to text DEFAULT 'tcandcompliance@collectiverealtyco.com'::text,
  google_review_link text,
  office_locations_html text,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tc_settings_pkey PRIMARY KEY (id),
  CONSTRAINT tc_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.homestead_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  county_name text NOT NULL,
  state text NOT NULL DEFAULT 'TX'::text,
  link_url text,
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT homestead_links_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tc_test_sends (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  template_slug text,
  sent_by_user_id uuid,
  from_email text NOT NULL,
  to_email text NOT NULL,
  subject_resolved text,
  body_resolved text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text])),
  graph_message_id text,
  sent_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tc_test_sends_pkey PRIMARY KEY (id),
  CONSTRAINT tc_test_sends_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.tc_email_templates(id),
  CONSTRAINT tc_test_sends_sent_by_user_id_fkey FOREIGN KEY (sent_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.email_signatures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  layout text NOT NULL CHECK (layout = ANY (ARRAY['classic'::text, 'stacked'::text, 'noLogo'::text, 'mobile'::text])),
  form_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  photo_url text,
  photo_url_square text,
  logo_url text,
  logo_url_square text,
  cta_image_url text,
  cta_link text,
  border_color text DEFAULT '#000000'::text,
  show_border boolean DEFAULT true,
  signature_type text DEFAULT 'with-photo'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  html_content text,
  CONSTRAINT email_signatures_pkey PRIMARY KEY (id),
  CONSTRAINT email_signatures_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.help_articles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  article_type text NOT NULL DEFAULT 'help'::text CHECK (article_type = ANY (ARRAY['help'::text, 'policy'::text])),
  category text,
  excerpt text,
  body text NOT NULL,
  cover_image_url text,
  published boolean DEFAULT false,
  order_index integer DEFAULT 0,
  view_count integer DEFAULT 0,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT help_articles_pkey PRIMARY KEY (id),
  CONSTRAINT help_articles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT help_articles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.pm_lease_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lease_id uuid NOT NULL,
  document_name text NOT NULL,
  file_url text NOT NULL,
  file_name text NOT NULL,
  onedrive_path text NOT NULL,
  uploaded_by uuid,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pm_lease_documents_pkey PRIMARY KEY (id),
  CONSTRAINT pm_lease_documents_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES public.pm_leases(id),
  CONSTRAINT pm_lease_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.landlord_disbursement_deductions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  disbursement_id uuid,
  landlord_id uuid NOT NULL,
  property_id uuid NOT NULL,
  label text NOT NULL,
  description text,
  amount numeric NOT NULL,
  incurred_date date,
  applied_at timestamp with time zone,
  sort_order integer NOT NULL DEFAULT 0,
  created_by uuid,
  source_repair_id uuid UNIQUE,
  source_invoice_id uuid UNIQUE,
  is_recurring boolean NOT NULL DEFAULT false,
  recurring_start_date date,
  recurring_end_date date,
  CONSTRAINT landlord_disbursement_deductions_pkey PRIMARY KEY (id),
  CONSTRAINT landlord_disbursement_deductions_disbursement_id_fkey FOREIGN KEY (disbursement_id) REFERENCES public.landlord_disbursements(id),
  CONSTRAINT landlord_disbursement_deductions_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id),
  CONSTRAINT landlord_disbursement_deductions_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.managed_properties(id),
  CONSTRAINT landlord_disbursement_deductions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT landlord_disbursement_deductions_source_repair_id_fkey FOREIGN KEY (source_repair_id) REFERENCES public.repair_requests(id),
  CONSTRAINT landlord_disbursement_deductions_source_invoice_id_fkey FOREIGN KEY (source_invoice_id) REFERENCES public.tenant_invoices(id)
);
CREATE TABLE public.tenant_disbursements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  tenant_id uuid NOT NULL,
  landlord_id uuid NOT NULL,
  property_id uuid NOT NULL,
  amount numeric NOT NULL,
  period_month integer NOT NULL CHECK (period_month >= 1 AND period_month <= 12),
  period_year integer NOT NULL CHECK (period_year >= 2020 AND period_year <= 2100),
  payment_status text NOT NULL DEFAULT 'pending'::text,
  payment_date date,
  notes text,
  CONSTRAINT tenant_disbursements_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_disbursements_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_disbursements_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id),
  CONSTRAINT tenant_disbursements_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.managed_properties(id)
);
CREATE TABLE public.zoom_recording_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  meeting_title text NOT NULL,
  start_time timestamp with time zone NOT NULL,
  mp4_download_url text NOT NULL,
  mp4_file_size bigint,
  zoom_token text NOT NULL,
  suggested_title text,
  suggested_folder text,
  final_title text,
  final_folder text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'uploaded'::text, 'error'::text])),
  sharepoint_url text,
  uploaded_at timestamp with time zone,
  error_message text,
  zoom_share_url text,
  onedrive_url text,
  onedrive_item_id text,
  meeting_id text,
  transcript_text text,
  zoom_summary text,
  chat_text text,
  zoom_recording_id text,
  notification_sent boolean NOT NULL DEFAULT false,
  notification_hold_since timestamp with time zone,
  sharepoint_item_id text,
  link_verify_pending boolean NOT NULL DEFAULT false,
  link_verify_attempts integer NOT NULL DEFAULT 0,
  CONSTRAINT zoom_recording_jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fathom_meetings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fathom_recording_id bigint NOT NULL UNIQUE,
  recording_date date NOT NULL,
  share_url text,
  transcript_text text,
  summary text,
  speakers ARRAY,
  duration_minutes integer,
  fetched_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fathom_meetings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.insights_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  date_from date NOT NULL,
  date_to date NOT NULL,
  report_json jsonb NOT NULL,
  CONSTRAINT insights_reports_pkey PRIMARY KEY (id),
  CONSTRAINT insights_reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.pm_landlord_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  landlord_id uuid NOT NULL,
  property_id uuid NOT NULL,
  period_month integer NOT NULL CHECK (period_month >= 1 AND period_month <= 12),
  period_year integer NOT NULL CHECK (period_year >= 2020 AND period_year <= 2100),
  amount numeric NOT NULL,
  description text,
  due_date date NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'paid'::text, 'cancelled'::text])),
  paid_at timestamp with time zone,
  paid_amount numeric,
  payment_method text,
  payment_notes text,
  payload_invoice_id text,
  payload_payment_link_id text,
  payload_payment_link_url text,
  notes text,
  CONSTRAINT pm_landlord_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT pm_landlord_invoices_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id),
  CONSTRAINT pm_landlord_invoices_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.managed_properties(id)
);
CREATE TABLE public.pm_statements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  landlord_id uuid NOT NULL,
  property_id uuid NOT NULL,
  period_type text NOT NULL CHECK (period_type = ANY (ARRAY['monthly'::text, 'annual'::text])),
  period_month integer CHECK (period_month >= 1 AND period_month <= 12),
  period_year integer NOT NULL,
  statement_date date NOT NULL DEFAULT CURRENT_DATE,
  total_rent_collected numeric NOT NULL DEFAULT 0,
  total_management_fees numeric NOT NULL DEFAULT 0,
  total_deductions numeric NOT NULL DEFAULT 0,
  total_deposits_in numeric NOT NULL DEFAULT 0,
  total_deposits_returned_to_landlord numeric NOT NULL DEFAULT 0,
  total_deposits_refunded_to_tenant numeric NOT NULL DEFAULT 0,
  total_net_disbursed numeric NOT NULL DEFAULT 0,
  held_in_trust_at_statement_date numeric NOT NULL DEFAULT 0,
  sent_at timestamp with time zone,
  sent_to_email text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  total_net_pending numeric NOT NULL DEFAULT 0,
  access_token text,
  total_owner_charges numeric NOT NULL DEFAULT 0,
  owner_charges_breakdown jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_admin_fees_crc numeric NOT NULL DEFAULT 0,
  admin_fees_breakdown jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT pm_statements_pkey PRIMARY KEY (id),
  CONSTRAINT pm_statements_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id),
  CONSTRAINT pm_statements_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.managed_properties(id),
  CONSTRAINT pm_statements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.zoom_meeting_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  zoom_recording_job_id uuid,
  meeting_id text NOT NULL,
  participant_name text,
  participant_email text,
  duration_minutes integer,
  join_time timestamp with time zone,
  leave_time timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT zoom_meeting_participants_pkey PRIMARY KEY (id),
  CONSTRAINT zoom_meeting_participants_zoom_recording_job_id_fkey FOREIGN KEY (zoom_recording_job_id) REFERENCES public.zoom_recording_jobs(id)
);
CREATE TABLE public.transaction_additional_income (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  transaction_id uuid NOT NULL,
  side text NOT NULL CHECK (side = ANY (ARRAY['listing'::text, 'buying'::text])),
  label text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  CONSTRAINT transaction_additional_income_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_additional_income_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.coaching_schedule_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  section text NOT NULL CHECK (section = ANY (ARRAY['coaching'::text, 'division'::text])),
  display_title text NOT NULL UNIQUE,
  outlook_event_id text,
  recurrence_type text NOT NULL DEFAULT 'weekly'::text,
  recurrence_day text NOT NULL DEFAULT 'monday'::text,
  start_time text NOT NULL DEFAULT '12:00'::text,
  end_time text NOT NULL DEFAULT '13:00'::text,
  description text NOT NULL DEFAULT ''::text,
  platform text NOT NULL DEFAULT ''::text,
  audience text NOT NULL DEFAULT ''::text,
  host text,
  highlight boolean NOT NULL DEFAULT false,
  image_url text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  event_location text NOT NULL DEFAULT ''::text,
  CONSTRAINT coaching_schedule_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agent_form_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  form_id uuid,
  agent_id uuid NOT NULL,
  submitted_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'submitted'::text,
  transaction_id uuid,
  listing_id uuid,
  data jsonb DEFAULT '{}'::jsonb,
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  CONSTRAINT agent_form_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT agent_form_submissions_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id),
  CONSTRAINT agent_form_submissions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id),
  CONSTRAINT agent_form_submissions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT agent_form_submissions_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id),
  CONSTRAINT agent_form_submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.agent_referral_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  form_submission_id uuid,
  referring_agent_id uuid,
  receiving_agent_id uuid,
  office_or_team text,
  is_team_lead boolean DEFAULT false,
  team_lead_email text,
  lead_name text,
  lead_email text,
  lead_phone text,
  lead_details text,
  referral_fee_lease text,
  referral_fee_sale text,
  notes text,
  email_sent_at timestamp with time zone,
  CONSTRAINT agent_referral_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT agent_referral_submissions_referring_agent_id_fkey FOREIGN KEY (referring_agent_id) REFERENCES public.users(id),
  CONSTRAINT agent_referral_submissions_receiving_agent_id_fkey FOREIGN KEY (receiving_agent_id) REFERENCES public.users(id),
  CONSTRAINT agent_referral_submissions_form_submission_id_fkey FOREIGN KEY (form_submission_id) REFERENCES public.agent_form_submissions(id)
);
CREATE TABLE public.agent_invoice_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  form_submission_id uuid,
  agent_id uuid NOT NULL,
  self_send boolean DEFAULT true,
  office_fee_paid boolean DEFAULT false,
  office_fee_invoice_id text,
  client_name text,
  property_name text,
  billing_address text,
  billing_email text,
  billing_contact text,
  vendor_setup text,
  move_in_date date,
  rental_address text,
  unit text,
  bedrooms text,
  rent_amount numeric,
  lease_term_months integer,
  commission_rate text,
  payout_timeframe text,
  notes text,
  transaction_id uuid,
  check_id uuid,
  generated_invoice_id text,
  invoice_status text DEFAULT 'draft'::text,
  CONSTRAINT agent_invoice_requests_pkey PRIMARY KEY (id),
  CONSTRAINT agent_invoice_requests_form_submission_id_fkey FOREIGN KEY (form_submission_id) REFERENCES public.agent_form_submissions(id),
  CONSTRAINT agent_invoice_requests_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id),
  CONSTRAINT agent_invoice_requests_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT agent_invoice_requests_check_id_fkey FOREIGN KEY (check_id) REFERENCES public.checks_received(id)
);
CREATE TABLE public.transaction_post_closing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transaction_id uuid NOT NULL UNIQUE,
  final_settlement_received boolean DEFAULT false,
  final_settlement_received_at timestamp with time zone,
  survey_received boolean DEFAULT false,
  survey_received_at timestamp with time zone,
  homestead_email_sent boolean DEFAULT false,
  homestead_email_sent_at timestamp with time zone,
  buyer_walkthrough_received boolean DEFAULT false,
  buyer_walkthrough_received_at timestamp with time zone,
  notes text,
  updated_by uuid,
  status text DEFAULT 'not_started'::text,
  completed_at timestamp with time zone,
  CONSTRAINT transaction_post_closing_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_post_closing_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT transaction_post_closing_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.tenant_invoice_charges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  tenant_invoice_id uuid NOT NULL,
  property_id uuid NOT NULL,
  landlord_id uuid NOT NULL,
  label text NOT NULL,
  amount numeric NOT NULL,
  description text,
  destination text NOT NULL DEFAULT 'owner'::text,
  created_by uuid,
  CONSTRAINT tenant_invoice_charges_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_invoice_charges_tenant_invoice_id_fkey FOREIGN KEY (tenant_invoice_id) REFERENCES public.tenant_invoices(id)
);
CREATE TABLE public.staging_csv_headers (
  Paid text,
  Flyer Sent text,
  Closing Date text,
  Post Closing Compliance - mark complete or incomplete text,
  Type "Complete" with date when compliance review is complete text,
  Completion time text,
  Agent Name text,
  Team text,
  Property Address text,
  Unit text,
  Type text,
  Type If Referred Out text,
  Apartment or other Lease Type text,
  Lease Term in Months text,
  Client Name text,
  Client Email text,
  Lead Source text,
   Commission Based Sales or Rent Price  text,
  Total Sales or Rent Price text,
  Expedite? text,
  Is commission based on the price listed above? If not, please e text,
  Commission Amount/Rate text,
  BTSA text,
  Buyer / Seller Rebate text,
  Title Company Contact Name text,
  Title Company Contact Email Address text,
  Loan Type text,
  Internal Referral? text,
  External Referral? text,
  External Referral Fee text,
  Additional Notes text,
  Division text,
  Notes text,
  Baccarat Tumblers text,
  Commission Based Sales or Rent Price text
);
CREATE TABLE public.deals (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  client_email text NOT NULL,
  property_address text NOT NULL,
  closing_date date,
  agent_name text,
  client_name text,
  total_sales_or_rent_price numeric,
  paid boolean,
  source_submission_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT deals_pkey PRIMARY KEY (id)
);
